app/models.py
from flask.ext.login import UserMixin
from . import login_manager, db
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    email = db.Column(db.String(64), unique=True, index=True)
    dob = db.Column(db.Date(), default=datetime.utcnow)

    def __repr__(self):
        return '<User %r>' % self.username

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    # Flask-Login integration
    def is_authenticated(self):
        return False

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id


class Restaurant(db.Model):
    __tablename__ = 'restaurant'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, index=True)
    speciality = db.Column(db.String(64))
    menu_table = db.relationship('Menu', backref='byRestaurant', lazy='dynamic')
    def __repr__(self):
        return '<restaurant %r>' % self.name


class Menu(db.Model):
    __tablename__ = 'menu'
    id = db.Column(db.Integer, primary_key=True)
    reciepe = db.Column(db.String(64), index=True)
    cost = db.Column(db.Integer)
    restaurant_id = db.Column(db.Integer, db.ForeignKey('restaurant.id'))

    def __repr__(self):
        return '<Menu %r>' % (self.reciepe)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField, IntegerField, TextAreaField
from wtforms.validators import Required


class Number(Form):
    amount = IntegerField("", validators=[Required()])
    submit = SubmitField("Add")

app/__init__.py
from flask import Flask
from flask.ext.mail import Mail
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.bootstrap import Bootstrap
from flask.ext.moment import Moment
from config import config
from flask.ext.login import LoginManager
from flask_wtf import CsrfProtect

login_manager = LoginManager()
mail = Mail()
bootstrap = Bootstrap()
db = SQLAlchemy()
moment = Moment()
csrf = CsrfProtect()

login_manager.session_protection = 'basic'                    #strong should be in production build
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    db.init_app(app)
    csrf.init_app(app)
    mail.init_app(app)
    bootstrap.init_app(app)
    moment.init_app(app)
    login_manager.init_app(app)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint, url_prefix='/main')
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
from . import views

app/main/views.py
from flask import render_template, abort, redirect, url_for, session
from . import main
from .forms import Number
from flask.ext.login import login_required
from ..models import User, Restaurant, Menu


@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    return render_template('main/user.html', user=user)


@main.route('/user/list')
@login_required
def list():
    restaurants = Restaurant.query.order_by(Restaurant.name).all()
    return render_template('main/list.html', restaurants=restaurants)


@main.route('/user/<int:id>', methods=['GET', 'POST'])
@login_required
def menu(id):
    number = Number()
    restaurant = Restaurant.query.get_or_404(id)
    menu = restaurant.menu_table.all()
    menulist = Menu.query.get_or_404(id)
    number.amount.data = 1
    if number.validate_on_submit():
        multiplier = number.amount.data
        total = multiplier
        cart = []
        cart.append([menu, multiplier, total])
        return redirect(url_for('main.menu', restaurant=restaurant.name, menu=menu, form=number))
    return render_template('main/menu.html', restaurant=restaurant.name, menu=menu, form=number, cart=[])

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}LaKhaana|Home{% endblock %}

{% block head%}
{{super()}}
<link rel="icon" type="image/x-icon" href="{{url_for('static', filename='logo_pure.png')}}">
<link rel="shortcut" type="image/x-icon" href="{{url_for('static', filename='logo_pure.png')}}">
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      {% if current_user.is_authenticated %}
      <a class="navbar-brand" href="{{url_for('main.list')}}">
        <!--<img alt="LaKhaana" src="#">-->
        Lakhaana
      </a>
      {% else %}
      <a class="navbar-brand" href="{{url_for('auth.login')}}">
        <!--<img alt="LaKhaana" src="#">-->
        Lakhaana
      </a>
      {% endif %}
    </div>
    <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="#">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url_for('main.user', username=current_user.username) }}">Profile</a></li>
                        <li><a href="#">Your Orders</a></li>
                        <li><a href="#">Settings</a></li>
                        <li><a href="{{url_for('auth.logout')}}">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="#">Log In</a></li>
                {% endif %}
            </ul>
        </div>
  </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/main/list.html
{% extends 'base.html' %}

{% block page_content %}
<div class="page-header">
	<h1>List of Restaurants</h1>
</div>
<div class="col-md-4">
	{%  for restaurant in restaurants %}
	<div style="margin-left:30px;border:3px solid #616161;margin-top:10px;height:160px;">
		<h4 style="font-weight:bold;margin-left:10px">{{restaurant.name}}</h4>
		<p style="margin-left:20px;">Speciality:{{restaurant.speciality}}</p>
		<p style="margin-left:20px;">Rating : 5 star</p>
		<a style="position: absolute;right: 20px; margin:10px;" href="{{url_for('main.menu', id=restaurant.id)}}" class="btn btn-primary" role="button">Menu</a>
	</div>
	{% endfor %}

</div>
{% endblock %}

app/templates/main/menu.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}LaKhaana{% endblock %}

{% block page_content %}
<div class="page-header">
	<h1>{{restaurant}}</h1>
</div>
<div class="col-md-4">
	<h3>Menu</h3>
	{% for m in menu%}
	<div style="margin-left:30px;border:3px solid #616161;margin-top:10px;height:180px;">
		<h5 style="font-weight:bold;margin-left:30px;">{{m.reciepe}}</h5>
		<p style="margin-left:30px;">Rs.{{m.cost|float}}</p>
		<div style="width:100px;position: absolute;right: 20px; margin:2px;">{{wtf.quick_form(form)}}</div>
	</div>
	{% endfor %}
</div>
<div class="col-md-4">
	<h3>Cart</h3>
	{% for c in cart %}
	<div>
		{%  for i in c%}
		<p>{{i}}</p>
		<br>
		{% endfor %}
		<a style="position: absolute;right: 20px; margin:10px;" href="#" class="btn btn-primary" role="button">Proceed to Checkout</a>
	</div>
	{% else %}
	<h6>No items added</h6>
	{% endfor %}
	</div>
</div>
{% endblock %}

{% block scripts%}
<script type="text/javascript">
	function pass_data (var cost) {
		
	}
</script>
{% endblock %}

app/templates/main/user.html
{% extends 'base.html' %}

{% block page_content %}
<div class="page-header">
	<h1 style="margin:40px">{{user.username}}</h1>
	<h5 style="margin:40px">Name  : {{user.username}}</h5>
	<h5 style="margin:40px">Email : {{user.email}}</h5>
	<h5 style="margin:40px">Password : ***********</h5>
	<h5 style="margin:40px">Date of Birth : {{moment(user.dob).format('L')}}</h5>
</div>
{% endblock %}